### ISSUE TITLE
What are some good ways for current students or new grads to connect with potential employers?

### ISSUE THREAD

**Issue by mattsre** [swyxio/ama#10]

**Comment by swyxio** [comment]
There are two forms of sales in the modern tech sales lingo: [inbound sales and outbound sales](https://www.bayt.com/en/specialties/q/70541/what-s-the-difference-between-outbound-sales-amp-inbound-sales/). Insofar as you are selling your services, this is a good mental model to think about your opportunity funnel.

**Overall**

This is a very messy, imperfect, high variation process. The only thing you can control is your process, not your outcome. Don't get discouraged when opportunities suddenly die. Shit happens. But your goal is to learn from even the stuff that didn't work out. What did you learn about interviewing? What did you learn about the job and would you want to do what they do? That kind of thing.

**Your process** is not just how you look for a job, but also how you **continually refine what you look for**. [Life punishes the vague wish and rewards the specific ask.](https://lisalarter.com/tim-ferriss-rocked-my-world/). The more specific you are about what you want (the more you know about your interests), the better for you. Your end goal is to know so damn much about the job you want that you're practically already in it. People will notice.

Its ok to not know what you want, and aim for "good enough" rather than "perfect".

**Inbound sales**

- Let people know you are open for business. Everyone who knows you should know you have availability, even if they don't work in tech, so that when they meet someone who is looking for someone like you or even vaguely in the same line of business as your "specific ask".
- Create content (blogposts, tweets, videos, github repos, whatever) about whatever you're interested in learning and [Learn in Public](https://gist.github.com/sw-yx/9720bd4a30606ca3ffb8d407113c0fe5). As surprising as it sounds, **there is not enough good technical content in the world.** Go where your employers are (eg Twitter) and engage. Occasionally mention you are open for business.

**Outbound sales**

- Reach out for coffee. This is one of those awkward things but you just gotta do it. They don't need you to buy them coffee, duh. But they know what you're trying to do and most people don't mind. You can also offer alternatives to coffee like going for a walk around the block if the weather is nice. Your goal is NOT to get a referral into the company. If they're meeting up with you, you're gonna get a referral anyway. Your goal is to learn everything you can about the job and company, and to put yourself in that person's shoes.
- Go to meetups and conferences. Everyone speaking is probably hiring. Go talk to them afterward. If they're swamped with people, pass them a nice note or a card with your contact details.
- (Aggressive move but smart for developers) - make a custom site/project specifically for that one company and lay out why you are a good fit for that company. [This guy got himself hired by Chance the Rapper.](https://chancehirehospey.com/). [This guy Facebook targeted the Reddit CEO](https://news.ycombinator.com/item?id=17110385). I'm talking EXTREME dedication to bust through the masses of noncommittal people. Obviously only do this for companies you truly actually care about.

thats all i've got for now. thanks for the question!
