### ISSUE TITLE
Netlify Prerendering feature with Create React App vs Gatsby

### ISSUE THREAD

**Issue by cmcaboy** [swyxio/ama#12]
Hey Sean,

I am trying to wrap my head around [Netlify Prerendering](https://docs.netlify.com/site-deploys/post-processing/prerendering/) in context to Create React app, a server rendered React App (Next.js), and a static site (Gatsby). Does Netlify prerendering make Gatsby unnecessary? Is there an impact on SEO as well?

Thanks!

**Comment by swyxio** [comment]
hi! no, it doesn't make Gatsby unnecessary. Yes, there is a positive impact on SEO.

Netlify Prerendering responds solely to search engine crawler requests, so that they can index your site information better. This is important for CRA content to show up on Google in a timely fashion instead of taking up to a month to index.

However SEO isn't the only reason to prerender content. You may also want to serve prerendered content to _users_, because it is faster (faster than responding from a central server, faster to download over the wire, faster to render on a phone). For that you will have to use Gatsby or Next.js, not Netlify Prerendering.

hope that helps!

**Comment by cmcaboy** [comment]
Awesome Sean! That clears things up for me. 

Thank you so much for the response!
