### ISSUE TITLE
Applying the 20-80 rule, what resources and/or strategies do you recommend for learning finance as a developer?

### ISSUE THREAD

**Issue by lucidsif** [swyxio/ama#2]

**Comment by swyxio** [comment]
Hmm. Finance is such a broad category that its hard to give good advice. So breaking it down:

- Personal finance: Stanford CS007 [Personal Finance For Engineers](https://cs007.blog/)
- Investing: Focus on asset allocation (eg [Meb Faber](http://mebfaber.com/2017/12/13/episode-86-quantitative-approach-tactical-asset-allocation/), [Cliff Asness](http://pages.stern.nyu.edu/~lpederse/papers/ValMomEverywhere.pdf)) more than individual company valuation (eg Buffett, Graham and Dodd) because you're not going to do it full-time 
- Company financials: Just learn basic accounting, eg the 3 basic financial statements Income Statement, Balance Sheet, Cash Flow statement, and the reason we have these three things.
- Fundraising: [Venture Deals](https://www.feld.com/archives/2016/10/venture-deals-third-edition.html) by Brad Feld

I guess these are the four main areas of finance that I consider relevant. There's a lot of finance that is more economics than finance, and that is both more interesting and important as well as more uncertain (if the Federal reserve hikes rates by 50 basis points, is that good or bad for the economy? If we shift from progressive to flat taxes is that good or bad? so on and so forth).

**Comment by lucidsif** [comment]
I see, thanks for breaking down such a broad category. I didn't know where to start, but now I'm aware of some of the branches to explore.
