### ISSUE TITLE
What are some factors that you consider important during the hiring practice?

### ISSUE THREAD

**Issue by mattsre** [swyxio/ama#7]
Essentially, if you were interviewing a candidate, what would you look for? What would make them stand out in a good way?

**Comment by swyxio** [comment]
I have never hired anyone, so I dont have direct experience. What matters to me most is whether they pass the [airport test](https://www.themuse.com/advice/the-airport-test-the-interview-assessment-you-didnt-know-you-were-getting) since i think most things are learnable so i dont really care about testing specific knowledge. of course if they have prior experience i want to see what they learned from those experiences. I also particularly like engineers that communicate well because code is only one part of what we do.
